//Game specific
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define TILESHEET_SIZE 21
#define MAP_SIZE 40
#define GRAVITY 9.81
#define NORMAL_FORCE -9.81
#define SCALING 2

//Animations
enum { WALK, RUN, IDLE, JUMP, FLY, ATTACK, FALL, LAND, PERISH };

//ENTITY TYPES
enum { PLAYER, TERRAIN, PROJECTILE, ENEMY };
