//Game specific
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define TILESHEET_SIZE 32
#define TILESHEET_X 89
#define TILESHEET_Y 62
#define MAP_SIZE 40
#define GRAVITY 9.81
#define NORMAL_FORCE -9.81
#define SCALING 1

//Animations
enum { WALK, RUN, IDLE, JUMP, FLY, ATTACK, FALL, LAND, PERISH, HURT };

//ENTITY TYPES
enum { PLAYER, TERRAIN, PROJECTILE, ENEMY };
